### ISSUE TITLE
[프로젝트 관리] 'branch' / 'commit message' / 'issue' 규칙

### ISSUE THREAD

**Issue by parkyounghwan** [10-miles/watch-subscribe#1]
## branch 관리
* **개별 브랜치 (이슈 기반 브랜치)**
1. 예를들어, 'yh-issue-1' [이름약어]-issue-[이슈번호]
2. 만약, local repository 에서 브랜치 생성하면, 바로 github 에 push
3. 컴퓨터 끄기 전에 꼭 push 하기
4. 가장 작은 기능 단위로 브랜치 생성해서 적어도 하루에 2 브랜치 생성할 수 있도록 노력

* **'dev'**
1. 개발 통합 브랜치로 구성원 각자 개발한 코드를 커밋
2. 개별 브랜치에서 개발 후 push 전, 꼭 local repository 에서 merge 후 push 하기
3. 'rebase' 를 적극 활용해서 커밋 로그를 깔끔하게 유지하기

* **'master'**
1. 배포용 브랜치로 'dev' 브랜치에서 만 커밋 가능
2. 배포 시, 버저닝 하기

## commit message 
* **로컬에서 'add' 하고, 'commit' 할 때**
1. git commit -m '#yh-issue-1, 커밋 메시지 규칙 작성' ('#[branch_name], commit message' 형식으로 작성)

## issue 발행
* 최대한 작게 잡을 것
* 이슈 제목에 이름 이니셜 빼기, 라벨링으로 대체

**Comment by BaeJi77** [comment]
근데 이거 왜 리드미에 작성안하고 여기에다가 작성하나요?
wiki에 작성해도 괜찮을 것 같은뎅ㅎㅎㅎㅎ

**Comment by parkyounghwan** [comment]
리드미는 프로젝트에 대한 소개만 작성하고, 이거는 위키로 옮기는게 맞는듯 .
확인했습니다.
